server:
  port: 8080
spring:
  application:
    name: inspection
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.111.237.66:3306/inspection?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
# redis:
#  host: 192.168.200.128
# Swagger界面内容配置
swagger:
  title: 安康专属API接口文档
  description: Safety Inspection Api Documentation
  version: 1.0.0
  termsOfServiceUrl: https://github.com/zuyunbo
  contact:
    name: 2u
    url: https://github.com/zuyunbo
    email: sy829322@163.com
mybatis:
  mapperLocations: classpath:mapper/*.xml #映射位置
  type-aliases-package: net.whir.hos.inspection.pc.bean  #对应实体类的路径
  configuration:
    mapUnderscoreToCamelCase: true #自动转驼峰
logging:
  level:
    net.whir.hos.inspection.pc.dao: DEBUG
#eureka:
# client:
#  service-url:
#   defaultZone: http://127.0.0.1:6868/eureka
# instance:
#  prefer-ip-address: true
#feign:
# hystrix:
#  enabled: true
# client:
#  config:
#   default:   #配置全局的feign的调用超时时间  如果 有指定的服务配置 默认的配置不会生效
#    connectTimeout: 60000 # 指定的是 消费者 连接服务提供者的连接超时时间 是否能连接  单位是毫秒
#    readTimeout: 80000  # 指定的是调用服务提供者的 服务 的超时时间（）  单位是毫秒
##hystrix 配置
#hystrix:
# command:
#  default:
#   execution:
#    timeout:
#     #如果enabled设置为false，则请求超时交给ribbon控制
#     enabled: true
#    isolation:
#     strategy: SEMAPHORE
#     thread:
#      # 熔断器超时时间，默认：1000/毫秒
#      timeoutInMilliseconds: 80000
#logging:
# level:
#  root: error  #打印日志到控制台  调试程序时可修改为 debug
#
##简单类型数据 String Integer  数组类型 集合类型 对象类型